
import './globals.css'
import { Inter } from 'next/font/google'
import ProviderSession from '@/components/Provider'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Youth-Led Social Entreprenuership',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderSession session={session}>
          <Navbar />
          <main>{children}</main>
        </ProviderSession>
      </body>
    </html>
  )
}
